
logdir: log
render: 0.0
seed: -1
lr: 0.00005

epoch: 100
buffer_size: 16384
step_per_epoch: 51200
test_num: 4
training_num: 8
step_per_collect: 1024
repeat_per_collect: 4
batch_size: 256

test:
  buffer_size: 1024
  step_per_epoch: 1024
  test_num: 1
  training_num: 2
  step_per_collect: 256
  repeat_per_collect: 3
  batch_size: 32

ppo_kwargs:
  discount_factor: 0.99
  max_grad_norm: 0.5
  eps_clip: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  gae_lambda: 0.95
  reward_normalization: 0
  dual_clip: null
  value_clip: 0
  deterministic_eval: False
  advantage_normalization: 1
  recompute_advantage: 0

task: hunter 

env_kwargs:
  train: 
    spawn_args: 'Z4C0/Z0C4'
  test:
    spawn_args: 'Z4C4'

obj_cat_nums:
  crafter: 9
  hunter: 5

space_logdirs:
  hunter: 'space_models/hunter'
  crafter: 'space_models/crafter'

pol_kwargs:
  mlp:
    latent_dim: 256
    net_arch: [256,256]
  smorl:
    L: 4
  ocarl:
    encoder:
      obj_cat_num: ${obj_cat_nums[${task}]}
      filters: [16,32,32]
      obs_shape: [64,64,3]
      enc_coeff: 0.01
    reasoning_layer:
      use_sep_mlp: true
  rrl: # make sure space.use_space == false.
    encoder:
      obj_cat_num: ${obj_cat_nums[${task}]}
      filters: [16,32,32]
      obs_shape: [64,64,3]
      enc_coeff: 0
    reasoning_layer:
      use_sep_mlp: false
pol_type: ocarl
G: 8
space:
  use_space: true
  cfg_path: ${space_logdirs[${task}]}/config.yaml
  kmeans_path: ${space_logdirs[${task}]}/pred_cat.model
